#!/usr/bin/env node
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { pathToFileURL } from "node:url";

const command = process.argv[2];

if (command === "init") {
  await runInit();
} else if (command === "sync") {
  await runSync();
} else {
  console.log("Usage: hub-kit <init|sync>");
  console.log("  init  Creates hub.config.mjs, a registry file and a starter adapter.");
  console.log("  sync  Reads hub.config.mjs and writes one route file per enabled page.");
  process.exit(command ? 1 : 0);
}

async function runInit() {
  const configTemplate = `export default {
  registryImport: "@/hub/registry",
  pages: [
    { component: "ActivityLogPage", path: "/activity-log" },
  ],
};
`;

  const registryTemplate = `import { ProcessingLogPage } from "@wt/hub-kit/pages";

import { processingLogAdapter } from "./adapters/processing-log";

export function ActivityLogPage() {
  return <ProcessingLogPage adapter={processingLogAdapter} />;
}
`;

  const adapterTemplate = `import type { ProcessingLogAdapter } from "@wt/hub-kit/adapters";

export const processingLogAdapter: ProcessingLogAdapter = {
  // Implement each member with your project's data layer.
};
`;

  writeFileIfMissing(resolve(process.cwd(), "hub.config.mjs"), configTemplate);
  writeFileIfMissing(resolve(process.cwd(), "src/hub/registry.tsx"), registryTemplate);
  writeFileIfMissing(resolve(process.cwd(), "src/hub/adapters/processing-log.ts"), adapterTemplate);

  console.log("");
  console.log("Add these two lines to your main CSS file:");
  console.log('  @import "@wt/hub-kit/themes/staey.css";');
  console.log('  @source "../node_modules/@wt/hub-kit/dist";');
  console.log("");
  console.log("Next steps:");
  console.log("  1. Fill in src/hub/adapters/processing-log.ts with your data layer.");
  console.log("  2. Add your pages to hub.config.mjs and bind them in src/hub/registry.tsx.");
  console.log("  3. Run: npx hub-kit sync");
}

function writeFileIfMissing(filePath, content) {
  if (existsSync(filePath)) {
    console.log(`kept ${filePath} (already exists)`);
    return;
  }
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, content);
  console.log(`wrote ${filePath}`);
}

async function runSync() {
  const configPath = resolve(process.cwd(), "hub.config.mjs");
  if (!existsSync(configPath)) {
    console.error("No hub.config.mjs found in this folder. Run: npx hub-kit init");
    process.exit(1);
  }

  const config = (await import(pathToFileURL(configPath).href)).default;

  if (!Array.isArray(config?.pages)) {
    console.error("hub.config.mjs must export default { pages: [...] }.");
    process.exit(1);
  }

  const routesFolder = resolve(process.cwd(), config.routesFolder ?? "src/routes");
  const registryImport = config.registryImport ?? "@/hub/registry";

  for (const page of config.pages) {
    if (!page.component || !page.path) {
      console.error(`Every page needs a component and a path. Got: ${JSON.stringify(page)}`);
      process.exit(1);
    }
    const routePath = page.path.endsWith("/") ? page.path : `${page.path}/`;
    const fileFolder = resolve(routesFolder, ...routePath.split("/").filter(Boolean));
    const filePath = resolve(fileFolder, "index.tsx");
    const depth = routePath.split("/").filter(Boolean).length;

    const fileContent = `// Generated by "hub-kit sync". Edit hub.config.mjs instead of this file.
import { createFileRoute } from "@tanstack/react-router";

import { ${page.component} } from "${registryImport}";

export const Route = createFileRoute("${routePath.slice(0, -1)}/")({
  component: ${page.component},
});
`;

    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, fileContent);
    console.log(`wrote ${filePath} (depth ${depth})`);
  }

  console.log(`Done: ${config.pages.length} route file(s).`);
}
