#!/usr/bin/env node
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { pathToFileURL } from "node:url";

const command = process.argv[2];

if (command !== "sync") {
  console.log("Usage: hub-kit sync");
  console.log("Reads hub.config.mjs and writes one route file per enabled page.");
  process.exit(command ? 1 : 0);
}

const configPath = resolve(process.cwd(), "hub.config.mjs");
if (!existsSync(configPath)) {
  console.error("No hub.config.mjs found in this folder.");
  process.exit(1);
}

const config = (await import(pathToFileURL(configPath).href)).default;

if (!Array.isArray(config?.pages)) {
  console.error("hub.config.mjs must export default { pages: [...] }.");
  process.exit(1);
}

const routesFolder = resolve(process.cwd(), config.routesFolder ?? "src/routes");
const registryImport = config.registryImport ?? "@/hub/registry";

for (const page of config.pages) {
  if (!page.component || !page.path) {
    console.error(`Every page needs a component and a path. Got: ${JSON.stringify(page)}`);
    process.exit(1);
  }
  const routePath = page.path.endsWith("/") ? page.path : `${page.path}/`;
  const fileFolder = resolve(routesFolder, ...routePath.split("/").filter(Boolean));
  const filePath = resolve(fileFolder, "index.tsx");
  const depth = routePath.split("/").filter(Boolean).length;

  const fileContent = `// Generated by "hub-kit sync". Edit hub.config.mjs instead of this file.
import { createFileRoute } from "@tanstack/react-router";

import { ${page.component} } from "${registryImport}";

export const Route = createFileRoute("${routePath.slice(0, -1)}/")({
  component: ${page.component},
});
`;

  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, fileContent);
  console.log(`wrote ${filePath} (depth ${depth})`);
}

console.log(`Done: ${config.pages.length} route file(s).`);
